# Generated by Django 3.2.10 on 2021-12-26 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='subscribe',
            field=models.ManyToManyField(blank=True, null=True, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
    ]
